# -*- coding: utf-8 -*-
"""week1 miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmilEanfpLqDpVg0z4-RDsdQ01hcW8eL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

DATA_DIR = "olist_data"

customers = pd.read_csv("olist_customers_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")

df = orders.merge(customers,on="customer_id")
df = df.merge(order_items,on="order_id")
df = df.merge(payments,on="order_id")
df = df.merge(products,on="product_id")

print(df.shape)

# First 5 Rows
print(df.head())

# Last 5 Rows
print(df.tail(5))

# Shape
print(df.shape)

# Columns
print(df.columns)

# Datatypes
print(df.dtypes)

# Missing Values
print(df.isnull().sum())

# Remove Duplicates
df = df.drop_duplicates()

# Fill Numeric Missing Values
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Fill Categorical Missing Values
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    df[col] = df[col].fillna("Unknown")

# Dataset Information
df.info()

# Statistical Summary
print(df.describe())

# loc
print(df.loc[0:5])

# Specific Columns
print(df.loc[0:5,["price","payment_value"]])

# iloc
print(df.iloc[0:5])

# Row and Column Position
print(df.iloc[0:5,0:5])

# High Price Products
high_price = df[df["price"] > 500]

print(high_price.shape)

# Delivered Orders
delivered = df[df["order_status"]=="delivered"]

print(delivered.shape)

# Ascending
print(df.sort_values("price").head())

# Descending
print(df.sort_values("price",ascending=False).head())

# Query Method
query_data = df.query("price > 100")

print(query_data.shape)

state_revenue = df.groupby("customer_state")["payment_value"].sum()

print(state_revenue.head())

category_sales = df.groupby("product_category_name")["price"].sum()

print(category_sales.head())

summary = df.groupby("customer_state").agg(
    Total_Revenue=("payment_value","sum"),
    Average_Price=("price","mean"),
    Order_Count=("order_id","count")
)

print(summary.head())

df["order_status"] = df["order_status"].replace(
    {
        "delivered":"Delivered",
        "shipped":"Shipped"
    }
)

df.rename(
    columns={"price":"Product_Price"},
    inplace=True
)

print(df.head())

numeric_df = df.select_dtypes(include=np.number)

print(numeric_df.corr())

plt.figure(figsize=(8,5))

plt.hist(df["Product_Price"],bins=30)

plt.title("Price Distribution")
plt.xlabel("Price")
plt.ylabel("Frequency")

plt.show()

top_states = df.groupby("customer_state")["payment_value"] \
               .sum() \
               .sort_values(ascending=False) \
               .head(10)

plt.figure(figsize=(10,5))

plt.bar(
    top_states.index,
    top_states.values
)

plt.title("Top States Revenue")
plt.xlabel("State")
plt.ylabel("Revenue")

plt.show()



payment_counts = df["payment_type"].value_counts()

plt.figure(figsize=(6,6))

plt.pie(
    payment_counts,
    labels=payment_counts.index,
    autopct="%1.1f%%"
)

plt.title("Payment Types")

plt.show()

plt.figure(figsize=(8,5))

plt.scatter(
    df["Product_Price"],
    df["freight_value"]
)

plt.xlabel("Price")
plt.ylabel("Freight Value")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="order_status"
)

plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(8,5))

plt.scatter(
    df["Product_Price"],
    df["payment_value"],
    alpha=0.5
)

plt.xlabel("Product Price")
plt.ylabel("Payment Value")
plt.title("Price vs Payment")

plt.show()

daily_orders = (
    df.groupby(
        pd.to_datetime(
            df["order_purchase_timestamp"]
        ).dt.date
    )["order_id"]
    .count()
)

x = range(len(daily_orders))
y = daily_orders.values

plt.figure(figsize=(12,5))

plt.plot(x, y)

plt.fill_between(
    x,
    y,
    alpha=0.4
)

plt.title("Daily Orders Trend")
plt.xlabel("Days")
plt.ylabel("Orders")

plt.show()

daily_orders = (
    df.groupby(
        pd.to_datetime(
            df["order_purchase_timestamp"]
        ).dt.date
    )["order_id"]
    .count()
)

x = range(len(daily_orders))
y = daily_orders.values

plt.figure(figsize=(12,5))

plt.plot(x, y,color = "red", linestyle="-",marker=".")

plt.fill_between(
    x,
    y,
    alpha=0.4
)

plt.title("Daily Orders Trend")
plt.xlabel("Days")
plt.ylabel("Orders")

plt.show()

plt.figure(figsize=(10,10))

sns.boxplot(
    data=df,
    y="order_purchase_timestamp",
    x="payment_type"
)

plt.show()

plt.figure(figsize=(10,5))

sns.countplot(
    data=df,
    x="order_status",
    hue="payment_type"
)

plt.xticks(rotation=45)

plt.title("Order Status by Payment Type")

plt.show()

top5 = df["payment_type"].value_counts().index[:5]

subset = df[df["payment_type"].isin(top5)]

plt.figure(figsize=(10,5))

sns.boxplot(
    data=subset,
    x="payment_type",
    y="Product_Price",
    hue="payment_type"
)

plt.show()

plt.figure(figsize=(10,5))

sns.violinplot(
    data=df,
    x="payment_type",
    y="payment_value",
    hue="payment_type"
)

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x="Product_Price",
    kde=True
)

plt.show()

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df.sample(5000),
    x="Product_Price",
    y="payment_value",
    hue="payment_type",
    palette="viridis"
)

plt.show()

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df.sample(5000),
    x="Product_Price",
    y="freight_value",
    hue="payment_type",
    size="payment_installments"
)

plt.show()

cols = [
    "Product_Price",
    "freight_value",
    "payment_value",
    "payment_installments",
    "product_weight_g"
]

sns.pairplot(df[cols].sample(1000))

plt.show()

daily_orders = (
    df.groupby(
        pd.to_datetime(
            df["order_purchase_timestamp"]
        ).dt.date
    )["order_id"]
    .count()
)

plt.figure(figsize=(12,5))

plt.plot(
    daily_orders.index,
    daily_orders.values
)

plt.title("Daily Orders Trend")
plt.xlabel("Date")
plt.ylabel("Orders")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.show()

plt.figure(figsize=(8,5))

sns.violinplot(
    data=df,
    x="payment_type",
    y="payment_value"
)

plt.show()

df.to_csv(
    "olist_cleaned_dataset.csv",
    index=False
)

print("Dataset Saved Successfully")

